language: java
script:

script: |-
  ./mvnw -B deploy \
  && echo 'testing... testing... testing...' \
  && curl -i -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -H "Content-Type:application/json" -X POST https://jbaruch.jfrog.io/jbaruch/api/build/promote/couchbase-javaee:$TRAVIS_BUILD_NUMBER -d '{"status": "released","comment" : "Automatically tested on all target platforms.","ciUser": "$USER","targetRepo" : "libs-release-local"}' /
  && echo 'triggering docker here'

install: echo 'installing'
jdk:
  - oraclejdk8
