language: java
script:

script: |-
  ./mvnw -B deploy \
  echo 'testing... testing... testing...' \
  echo 'promoting here' \
  echo 'triggering docker here'

install: echo 'installing'
jdk:
  - oraclejdk8
